apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: WebApplication
  description: The WebApplication API
  tags:
    - store
    - rest
  links:
    - url:https://github.com/guruprakashchinnasamy/TestBackstage
      title: GitHub Repo
      icon: github
    - url: https://github.com/guruprakashchinnasamy/TestBackstage/blob/main/weather.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  definition: |
   openapi: 3.0.1
   info:
   title: WebApplication1
   version: '1.0'
   paths:
   /WeatherForecast:
    get:
      tags:
        - WeatherForecast
      operationId: GetWeatherForecast
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
   components:
   schemas:
    WeatherForecast:
      type: object
      properties:
        date:
          type: string
          format: date-time
        temperatureC:
          type: integer
          format: int32
        temperatureF:
          type: integer
          format: int32
          readOnly: true
        summary:
          type: string
          nullable: true
      additionalProperties: false
